### ISSUE TITLE
[2] Add a range in XML file.

### ISSUE THREAD

**Issue by Edwix** [Edwix/VSObserver#11]
I want : 
To put a range in XML file

To get a certain value : 
To have a color in a certainly range of value

**Comment by alstomdounet** [comment]
In a prior approach, maybe that following solution can be used:

``` XML
   <Item>
       <Variable>_10A11_(66|64|40|54|8|9|39|10A11_10XP11_XC1_3)$</Variable>
       <RuleSet>
            <SimpleRule value="0" color="Green" operator="gt" />
            <SimpleRule value="0" color="Red" operator="le"  />
       </RuleSet>
   </Item>
```

where `operator` is one of `gt` (greater than), `lt` (lower than), `eq` (equals to - by default), `ge` (greater or equal than), `le` (lower or equal than).

rules are taken as they are defined in XML file (first rule match is the one which will define color).
