### ISSUE TITLE
Error while doing copy of text

### ISSUE THREAD

**Issue by alstomdounet** [Edwix/VSObserver#3]
This error appears sometime when performing copy/paste of texts inside VsObserver.

![detail of fatal error](https://cloud.githubusercontent.com/assets/1249284/6863311/65c2ec9a-d44f-11e4-8232-c9aef9ee0ff0.png)

**Comment by Edwix** [comment]
Here one solution: 
http://stackoverflow.com/questions/12769264/openclipboard-failed-when-copy-pasting-data-from-wpf-datagrid
