### ISSUE TITLE
Coloring of expected values

### ISSUE THREAD

**Issue by alstomdounet** [Edwix/VSObserver#5]
Priority : :one:
### I want

Within additionnal file, it would be possible to set specific color for specific values, for variables stored in this list. It must be refreshed when file is modified. Coloring rule must use REGEXES, with implicit `^` and `$` (see regex rules).
### Expected result

after listing variables, coloring rules on background of value cell has to be applied for any found variables. 

For regexes :
- `TEST` need to match only `TEST`, and NOT `TEST/VARIABLE`. 
- `TEST.*` needs to match both `TEST` and `TEST/VARIABLE`. 
- and so on.

**Comment by Edwix** [comment]
I propose this XML format :

``` XML
<List>
   <Item>
       <Variable>TEST</Variable>
       <RuleSet>
            <SimpleRule value="0" color="red" />
            <SimpleRule value="0" color="#00CC00" />
       </RuleSet>
   </Item>
</List>
```
